[postgres]
host = "YOUR_POSTGRES_HOST"
port = "5432"
database = "YOUR_DATABASE_NAME"
user = "YOUR_USERNAME"
password = "YOUR_PASSWORD"

[twilio]
account_sid = "YOUR_TWILIO_ACCOUNT_SID"
auth_token = "YOUR_TWILIO_AUTH_TOKEN"
from_number = "whatsapp:+14155238886"
